name: ShoppingCart-CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Clone
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
    - name: Restore
      run: dotnet restore --verbosity normal .\src\ShoppingCart\ShoppingCart.csproj
    - name: Build
      run: dotnet build --no-restore --configuration Release --verbosity normal .\src\ShoppingCart\ShoppingCart.csproj
    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal .\src\ShoppingCart\ShoppingCart.csproj
    - name: Publish
      run: dotnet publish --no-build --configuration Release --verbosity normal .\src\ShoppingCart\ShoppingCart.csproj
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ShoppingCart
        path: .\src\ShoppingCart\bin\Release\net8.0\publish